<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Cadmus.Epigraphy.Parts" Version="9.0.4" />
		<PackageReference Include="Cadmus.General.Parts" Version="15.0.1" />
		<PackageReference Include="Cadmus.Geo.Parts" Version="6.0.3" />
		<PackageReference Include="Cadmus.Import.Proteus" Version="15.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Cadmus.Tes.Parts\Cadmus.Tes.Parts.csproj" />
	</ItemGroup>

</Project>
