<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>Tes.Cli</RootNamespace>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Daniele Fusi</Authors>
		<Company>Fusi</Company>
		<Product>Cadmus</Product>
		<Description>CLI tool for the Cadmus TES Project.</Description>
		<Copyright>by Daniele Fusi 2026</Copyright>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.json" />
		<None Remove="Assets\Dump-md.json" />
		<None Remove="Assets\Import.json" />
		<None Remove="Assets\Thesauri.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Dump-md.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Dump-xlsx.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Import.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Thesauri.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Cadmus.Import.Proteus" />
		<PackageReference Include="Cadmus.Seed" />
		<PackageReference Include="Fusi.Cli.Logging" />
		<PackageReference Include="Fusi.Microsoft.Extensions.Configuration.InMemoryJson" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Proteus.Entries" />
		<PackageReference Include="Proteus.Extras" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Extensions.Hosting" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Spectre.Console" />
		<PackageReference Include="Spectre.Console.Cli" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug'">
		<ProjectReference Include="..\Cadmus.Tes.Import\Cadmus.Tes.Import.csproj" />
		<ProjectReference Include="..\Cadmus.Tes.Parts\Cadmus.Tes.Parts.csproj" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)'=='Release'">
		<PackageReference Include="Cadmus.Tes.Import" />
		<PackageReference Include="Cadmus.Tes.Parts" />
	</ItemGroup>

</Project>
