<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Authors>Daniele Fusi</Authors>
		<Company>Fusi</Company>
		<Product>Cadmus</Product>
		<Description>Miscellaneous parts specific to the Cadmus TES Project.</Description>
		<Copyright>by Daniele Fusi 2026</Copyright>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
		<PackageTags>Cadmus;parts</PackageTags>
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<!-- SourceLink-related -->
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<Deterministic>true</Deterministic>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug'">
		<PackageReference Include="Cadmus.Core" />
		<PackageReference Include="Cadmus.Geo.Parts" />
		<PackageReference Include="Cadmus.Mat.Bricks" />
		<PackageReference Include="Cadmus.Refs.Bricks" />
		<PackageReference Include="Cadmus.Seed.Geo.Parts" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)'=='Release'">
		<PackageReference Include="Cadmus.Core" />
		<PackageReference Include="Cadmus.Geo.Parts" />
		<PackageReference Include="Cadmus.Mat.Bricks" />
		<PackageReference Include="Cadmus.Refs.Bricks" />
		<PackageReference Include="Cadmus.Seed.Geo.Parts" />
	</ItemGroup>

</Project>
