<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Cadmus.Api.Config" />
		<PackageReference Include="Cadmus.Api.Controllers" />
		<PackageReference Include="Cadmus.Api.Controllers.Export" />
		<PackageReference Include="Cadmus.Api.Controllers.Import" />
		<PackageReference Include="Cadmus.Api.Models" />
		<PackageReference Include="Cadmus.Api.Services" />
		<PackageReference Include="Cadmus.Graph" />
		<PackageReference Include="Cadmus.Graph.Ef.PgSql" />
		<PackageReference Include="Cadmus.Graph.Extras" />
		<PackageReference Include="Cadmus.Seed" />
		<PackageReference Include="Cadmus.Seed.Codicology.Parts" />
		<PackageReference Include="Cadmus.Seed.Epigraphy.Parts" />
		<PackageReference Include="Cadmus.Seed.General.Parts" />
		<PackageReference Include="Cadmus.Seed.Philology.Parts" />
		<PackageReference Include="Fusi.Antiquity" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Polly" />
		<PackageReference Include="Scalar.AspNetCore" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Exceptions" />
		<PackageReference Include="Serilog.Extensions.Hosting" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.MongoDB" />
		<PackageReference Include="Serilog.Sinks.Postgresql.Alternative" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug'">
	  <ProjectReference Include="..\Cadmus.Seed.Tes.Parts\Cadmus.Seed.Tes.Parts.csproj" />
	  <ProjectReference Include="..\Cadmus.Tes.Parts\Cadmus.Tes.Parts.csproj" />
	  <ProjectReference Include="..\tes-tool\tes-tool.csproj" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)'=='Release'">
		<PackageReference Include="Cadmus.Seed.Tes.Parts" />
		<PackageReference Include="Cadmus.Tes.Parts" />
		<PackageReference Include="tes-tool" />
	</ItemGroup>

</Project>
